### ISSUE TITLE
Palabra de Gloria demasiado nerfeada

### ISSUE THREAD

**Issue by SoullYT** [demixitho3/Bugtracker_Monster2021#22]
La palabra de gloria en el nuevo core , esta demasiado nerf , deberia curar hasta 100k , en estos momentos solamente esta curando de 50 a 60k (recalcar que hablo de 100k en cd con colera vengativa  y en sacro)
id de la spell:85673
Pj: Soull

**Comment by demixitho3** [comment]
necesitamos saber cuando en % necesitamos subir a dicha spell

**Comment by Aquileswar** [comment]
Podrían subirle un 20% para ver si queda bien, dado el caso de que le falte le suben un poco más o si cura más le bajan un 5%. Pj aquileswar
